Feature/notification table
timbaev/PushNotifications pull request #6
Opened 2018-03-30 22:52 UTC by DamirZaripov

2018-03-30 23:12 UTC, timbaev requested changes
Так-то код красивый, мне нравится. Мелочи уж только тут

2018-03-30 23:12 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/Configurator/NotificationTableConfigurator.swift
> +    func setupModel(with viewController: NotificationTableViewController) {
setupModule

2018-03-30 23:12 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/Configurator/NotificationTableConfigurator.swift
> +        //let router = NotificationTableRouter()
а куда потерялся router?

2018-03-30 23:12 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/DataSource/NotificationTableDataSource.swift
> +    var currentNotificationImage: UIImage?
почисти неиспользуемые переменные

2018-03-30 23:12 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/DataSource/NotificationTableDataSource.swift
> +        return cellHeight
мы же умеем уже делать динамические ячейчки по высоте, пусть сам высчитывает, какая высота нужна

2018-03-30 23:12 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/DataSource/NotificationTableDataSource.swift
> +    var notifications: [NotificationCellModel]?
упс, а где абстракция?

2018-03-30 23:12 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/DataSource/NotificationTableDataSource.swift
> +    var notifications: [NotificationCellModel]?
и можно будет уже обозвать cellModels

2018-03-30 23:12 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/Helpers/UIImageViewExtension.swift
> +    func downloadedFrom(url: URL, contentMode mode: UIViewContentMode = .scaleAspectFit) {
ну вот, и для чего я библиотеку подключал? :(

2018-03-30 23:12 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/Interactor/NotificationTableInteractorInput.swift
> +    func getNotifications()
комменты если что генерируются так: alt+cmd+/

2018-03-30 23:12 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/NotificationCell/NotificationTableViewCell.swift
> +    override func setSelected(_ selected: Bool, animated: Bool) {
Лишние функции тоже можно убрать, загромождают код

2018-03-30 23:12 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/NotificationCell/NotificationTableViewCell.swift
> +            self.notificationImage.downloadedFrom(url: url)
оу-оу, ячейка умеет скачивать с инета, не есть гуд (она же view просто)
нужно подумать над этим (пока сам не знаю)

2018-03-30 23:12 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/Presenter/NotificationTablePresenter.swift
> +            //возможно кинуть аллерт или ничего не делать
Конечно alert бросай

2018-03-30 23:12 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/View/NotificationTableViewController.swift
> +        super.viewDidLoad()
по хорошему, здесь должен быть только один метод, типа presenter.viewIsReady()
а дальше уже presenter настраивает view

2018-03-30 23:12 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/Presenter/NotificationTablePresenter.swift
> +    func setNotifications() {
ну не, set это когда устанавливаешь значение какое-то. А тут у меня просто запрос на получение, собственно, лучше и обозвать getNotifications()

2018-03-30 23:12 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/View/NotificationTableViewController.swift
> +        presenter.setNotifications()
это работает корректно? Надеюсь, ты тестировал, прежде как отправить
Просто сомнения в том, что tableView.reloadData() вызовется раньше, чем успеют прийти данные (они же асинхронно подтягиваются)

2018-03-30 23:12 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/View/NotificationTableViewController.swift
> +        presenter.setNotifications()
Если всё норм, тогда хорошо :3

2018-03-30 23:12 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/View/NotificationTableViewController.swift
> +    func setCellModels(with notificationModels: [NotificationCellModel]) {
Абстракция? ☁️

2018-03-30 23:12 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/View/NotificationTableViewOutput.swift
> +    /// Setter
эт же метод на получение данных, какой ещё setter

2018-03-30 23:30 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/View/NotificationTableViewController.swift
> +        presenter.setNotifications()
А да, это сработает скорее всего, потому что мы же не асинхронно получаем. А так, можно на два метода разделить просто

2018-03-31 17:12 UTC, DamirZaripov commented
1) Добавил viewDidAppear, думал через него рефреш сделать, но таблица обновляется лишь если перейти на другой таб и вернуться. Видимо я не понимаю логику происходящего( 
2) Вместо динамической высоту предлагаю для пушек без фото выводить дефолтную фотку "нет фотографии"

2018-03-31 18:28 UTC, timbaev requested changes

2018-03-31 18:28 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/Configurator/NotificationTableConfigurator.swift
>          presenter.interactor = interactor
ой, забыли presenter.router = router

2018-03-31 18:28 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/DataSource/NotificationTableDataSource.swift
> +        return cellHeight
Ну, это же не есть гуд. А если текста много? Или наоборот мало? Смотрится норм?

2018-03-31 18:28 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/NotificationCell/NotificationTableViewCell.swift
> +    override func setSelected(_ selected: Bool, animated: Bool) {
А чего не убрал? :(

2018-03-31 18:28 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/NotificationCell/NotificationTableViewCell.swift
> +        notificationTitleLabel.text = notificationCellModel.text
ой, а вы трестируете код? :D

2018-03-31 18:28 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/Presenter/NotificationTablePresenter.swift
> +        getNotifications()
interactor.getNotifications()? 🤔

2018-03-31 18:28 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/View/NotificationTableViewController.swift
> +    func setCellModels(with notificationModels: [CellModel]) {
го лучше set(cellModels: [CellModels])
тип абстракция и в названиях там, тырым-пырым

2018-03-31 18:28 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/View/NotificationTableViewController.swift
> +        refreshControl.endRefreshing()
эм..и зачем эта штука?
Это штука срабатывает, когда ты потянул вниз.
Окей, ты потянул, и сразу же прекращаешь анимацию обновления. 
Может, обновим данные?

2018-03-31 18:28 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/View/NotificationTableViewController.swift
> +        tableView.delegate = inputDataSource
мы же делегат во View решили вынести

2018-03-31 18:28 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/View/NotificationTableViewInput.swift
> +    /// Retrieving data from Data Source
Retrieving data? Этот метод у тебя же создает связь tableView с datasource, а не получает данные.
Поправь, если не правильно понял перевод.

2018-03-31 18:28 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/View/NotificationTableViewOutput.swift
> +    /// Setter
/// Get notification models

2018-03-31 18:30 UTC, timbaev requested changes

2018-03-31 18:30 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/DataSource/NotificationTableDataSource.swift
> +        return 98
ну вот, взял и константу убрал. Downgrade кода?

2018-03-31 18:30 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/NotificationCell/NotificationTableViewCell.swift
> +        notificationImage.image = UIImage(named: "no-image")
А может просто скроем, или это сложно реализуемо?

2018-03-31 18:53 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/NotificationCell/NotificationTableViewCell.swift
> +        notificationImage.image = UIImage(named: "no-image")
Хотя, оставь это на меня, я попробую успеть потом сделать со скрытием

2018-03-31 22:24 UTC, timbaev requested changes
Уже совсем близко к цели

2018-03-31 22:24 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/Presenter/NotificationTablePresenter.swift
> +        view.reloadTableView()
зачем эта штука здесь??
у тебя и так после getNotifications() ответ приходит в didFinishingToGetNotifications(with result: Result<NotificationCellModel>)

2018-03-31 22:24 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/Presenter/NotificationTablePresenter.swift
> +        getNotifications()
не исправили :(

2018-03-31 22:24 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/Presenter/NotificationTablePresenter.swift
> +    func reloadNotificationData() {
у тебя метод выше будет делать тоже самое, не дублируй одно и тоже

2018-03-31 22:24 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/View/NotificationTableViewController.swift
> +        presenter.reloadNotificationData()
вот, а здесь будет просто presenter.getNotifications()

2018-03-31 22:24 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/View/NotificationTableViewController.swift
> +        return 98
константа :(

2018-03-31 22:24 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/View/NotificationTableViewInput.swift
> +    func setTableViewDelegate()
комментарии

2018-03-31 22:24 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/View/NotificationTableViewOutput.swift
> +    func reloadNotificationData()
комментарии

2018-03-31 23:21 UTC, timbaev approved these changes
Одно исправление и можно мержить

2018-03-31 23:21 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/Presenter/NotificationTablePresenter.swift
> +        getNotifications()
пишу в третий раз: interactor.getNotifications() 😢

2018-03-31 23:21 UTC, timbaev commented on OutSideInsidePushNotifications/Modules/NotificationTable/Presenter/NotificationTablePresenter.swift
> +            //возможно кинуть аллерт или ничего не делать
Лишь бы не забыть про это потом

2018-03-31 23:52 UTC, merged